### ISSUE TITLE
Option to list by name instead of uname

### ISSUE THREAD

**Issue by myblackrx** [XoopsModulesArchive/isearch#3]
i'm using XOOPS in an Intranet environment in my small office

it is a closed site with manual registration and all user are registered using their staff ID as username

i tried to replace uname to name in ...modules\isearch\admin\index.php
but having a half loading page....

so i would like to suggest an option in the preferences..

Thank You

**Comment by geekwright** [comment]
In isearch/class/searches.php, [on line 52](https://github.com/XoopsModulesArchive/isearch/blob/4ee6349f0dcd5912b26a6b1769f122c74ae5b50d/class/searches.php#L52) we have this:
```php
    $tblusers[$uid]=XoopsUser::getUnameFromId($uid);
```

Changing it to this:
```php
    $tblusers[$uid]=XoopsUser::getUnameFromId($uid, 1);
```
should cause the name lookup to be done using the name, rather than uname column. (And, if the name is blank, it defaults back to the uname.) You should be able to apply this hack to meet your immediate needs.

Switching the second parameter to `XoopsUser::getUnameFromId()` between 0 and 1 using a preference option would allow the choice between uname (for a 0, the default) and name (for a 1). That, by itself is not a big effort, if someone has the time to implement it. 

Based on the fact that it is under XoopsModulesArchive, it is likely that there will to be a number of things that might need attention once someone starts working on it.

**Comment by zyspec** [comment]
I've updated a few things, in [my fork](https://github.com/zyspec/isearch).  I just added a Preferences setting as @geekwright outlined above that should address #3

**Comment by myblackrx** [comment]
Thank you very much zyspec and geekwright ..XOOPS is wonderful :-)

**Comment by zyspec** [comment]
Changes have been tested and merged back into master.
